default: &default
  pool: 5
  adapter: mysql2
  host: localhost
  encoding: utf8

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: istrading_work
  username: istrading
  password: <%= ENV['ISTRADING_WORK_DATABASE_PASSWORD'] %>
